//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamilTv.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TamilTv.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ca-app-pub-5213150499806218/1902799875.
        /// </summary>
        internal static string ArticleFooterAd {
            get {
                return ResourceManager.GetString("ArticleFooterAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ca-app-pub-5213150499806218/2914954052.
        /// </summary>
        internal static string ArticleHeaderAd {
            get {
                return ResourceManager.GetString("ArticleHeaderAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ca-app-pub-5213150499806218/2140928439.
        /// </summary>
        internal static string CategoryFooterAd {
            get {
                return ResourceManager.GetString("CategoryFooterAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading \n old episodes.
        /// </summary>
        internal static string DownloadingOldEpisodes {
            get {
                return ResourceManager.GetString("DownloadingOldEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ca-app-pub-5213150499806218/6633857156.
        /// </summary>
        internal static string HomeFooterAd {
            get {
                return ResourceManager.GetString("HomeFooterAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ca-app-pub-5213150499806218/1535204028.
        /// </summary>
        internal static string HomeHeaderAd {
            get {
                return ResourceManager.GetString("HomeHeaderAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry !! Invalid content information for {0}.
        /// </summary>
        internal static string InvalidNavigationUrl {
            get {
                return ResourceManager.GetString("InvalidNavigationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet available ! Please check your internet connection. .
        /// </summary>
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now shows available !! 
        /// Please try again later.
        /// </summary>
        internal static string NoItemsAvailable {
            get {
                return ResourceManager.GetString("NoItemsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ca-app-pub-5213150499806218/1563124184.
        /// </summary>
        internal static string ProgramItemAd {
            get {
                return ResourceManager.GetString("ProgramItemAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ca-app-pub-5213150499806218/3809233328.
        /// </summary>
        internal static string VideoInterimAd {
            get {
                return ResourceManager.GetString("VideoInterimAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
